//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ClienteWs.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSCustumersSoap", Namespace="http://tempuri.org/")]
    public partial class WSCustumers : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BuscarCustumersOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarOrdenOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarEmployeesOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarProductoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSCustumers() {
            this.Url = global::ClienteWs.Properties.Settings.Default.ClienteWs_localhost_WSCustumers;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BuscarCustumersCompletedEventHandler BuscarCustumersCompleted;
        
        /// <remarks/>
        public event BuscarOrdenCompletedEventHandler BuscarOrdenCompleted;
        
        /// <remarks/>
        public event BuscarEmployeesCompletedEventHandler BuscarEmployeesCompleted;
        
        /// <remarks/>
        public event BuscarProductoCompletedEventHandler BuscarProductoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarCustumers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Custumers BuscarCustumers(int NumberOrder) {
            object[] results = this.Invoke("BuscarCustumers", new object[] {
                        NumberOrder});
            return ((Custumers)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarCustumersAsync(int NumberOrder) {
            this.BuscarCustumersAsync(NumberOrder, null);
        }
        
        /// <remarks/>
        public void BuscarCustumersAsync(int NumberOrder, object userState) {
            if ((this.BuscarCustumersOperationCompleted == null)) {
                this.BuscarCustumersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarCustumersOperationCompleted);
            }
            this.InvokeAsync("BuscarCustumers", new object[] {
                        NumberOrder}, this.BuscarCustumersOperationCompleted, userState);
        }
        
        private void OnBuscarCustumersOperationCompleted(object arg) {
            if ((this.BuscarCustumersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarCustumersCompleted(this, new BuscarCustumersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarOrden", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Ordes BuscarOrden(int NumberOrder) {
            object[] results = this.Invoke("BuscarOrden", new object[] {
                        NumberOrder});
            return ((Ordes)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarOrdenAsync(int NumberOrder) {
            this.BuscarOrdenAsync(NumberOrder, null);
        }
        
        /// <remarks/>
        public void BuscarOrdenAsync(int NumberOrder, object userState) {
            if ((this.BuscarOrdenOperationCompleted == null)) {
                this.BuscarOrdenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarOrdenOperationCompleted);
            }
            this.InvokeAsync("BuscarOrden", new object[] {
                        NumberOrder}, this.BuscarOrdenOperationCompleted, userState);
        }
        
        private void OnBuscarOrdenOperationCompleted(object arg) {
            if ((this.BuscarOrdenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarOrdenCompleted(this, new BuscarOrdenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarEmployees", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Employees BuscarEmployees(int OrderNumber) {
            object[] results = this.Invoke("BuscarEmployees", new object[] {
                        OrderNumber});
            return ((Employees)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarEmployeesAsync(int OrderNumber) {
            this.BuscarEmployeesAsync(OrderNumber, null);
        }
        
        /// <remarks/>
        public void BuscarEmployeesAsync(int OrderNumber, object userState) {
            if ((this.BuscarEmployeesOperationCompleted == null)) {
                this.BuscarEmployeesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarEmployeesOperationCompleted);
            }
            this.InvokeAsync("BuscarEmployees", new object[] {
                        OrderNumber}, this.BuscarEmployeesOperationCompleted, userState);
        }
        
        private void OnBuscarEmployeesOperationCompleted(object arg) {
            if ((this.BuscarEmployeesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarEmployeesCompleted(this, new BuscarEmployeesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Products[] BuscarProducto(int OrderNumber) {
            object[] results = this.Invoke("BuscarProducto", new object[] {
                        OrderNumber});
            return ((Products[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarProductoAsync(int OrderNumber) {
            this.BuscarProductoAsync(OrderNumber, null);
        }
        
        /// <remarks/>
        public void BuscarProductoAsync(int OrderNumber, object userState) {
            if ((this.BuscarProductoOperationCompleted == null)) {
                this.BuscarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarProductoOperationCompleted);
            }
            this.InvokeAsync("BuscarProducto", new object[] {
                        OrderNumber}, this.BuscarProductoOperationCompleted, userState);
        }
        
        private void OnBuscarProductoOperationCompleted(object arg) {
            if ((this.BuscarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarProductoCompleted(this, new BuscarProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Custumers {
        
        private int numberField;
        
        private string nameField;
        
        private string contactLastNameField;
        
        private string constactFirstNameField;
        
        private string phoneField;
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string postalField;
        
        private string countryField;
        
        private int salesRepEmployeeNumberField;
        
        private double creditLimitField;
        
        /// <remarks/>
        public int Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string ContactLastName {
            get {
                return this.contactLastNameField;
            }
            set {
                this.contactLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string ConstactFirstName {
            get {
                return this.constactFirstNameField;
            }
            set {
                this.constactFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string AddressLine1 {
            get {
                return this.addressLine1Field;
            }
            set {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        public string AddressLine2 {
            get {
                return this.addressLine2Field;
            }
            set {
                this.addressLine2Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Postal {
            get {
                return this.postalField;
            }
            set {
                this.postalField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public int SalesRepEmployeeNumber {
            get {
                return this.salesRepEmployeeNumberField;
            }
            set {
                this.salesRepEmployeeNumberField = value;
            }
        }
        
        /// <remarks/>
        public double CreditLimit {
            get {
                return this.creditLimitField;
            }
            set {
                this.creditLimitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Products {
        
        private string productCodeField;
        
        private string productNameField;
        
        private string productLineField;
        
        private string productScaleField;
        
        private string productVendedorField;
        
        private string productDescriptionField;
        
        private int quantityField;
        
        private double priceField;
        
        private double mSRPField;
        
        /// <remarks/>
        public string ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        public string ProductLine {
            get {
                return this.productLineField;
            }
            set {
                this.productLineField = value;
            }
        }
        
        /// <remarks/>
        public string ProductScale {
            get {
                return this.productScaleField;
            }
            set {
                this.productScaleField = value;
            }
        }
        
        /// <remarks/>
        public string ProductVendedor {
            get {
                return this.productVendedorField;
            }
            set {
                this.productVendedorField = value;
            }
        }
        
        /// <remarks/>
        public string ProductDescription {
            get {
                return this.productDescriptionField;
            }
            set {
                this.productDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public double Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public double MSRP {
            get {
                return this.mSRPField;
            }
            set {
                this.mSRPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Employees {
        
        private int employeeNumberField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        private string extensionField;
        
        /// <remarks/>
        public int EmployeeNumber {
            get {
                return this.employeeNumberField;
            }
            set {
                this.employeeNumberField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ordes {
        
        private int orderNumberField;
        
        private System.DateTime orderDateField;
        
        private System.DateTime requiredDateField;
        
        private System.DateTime shippedDateField;
        
        private string statusField;
        
        private string commentsField;
        
        private int customerNumberField;
        
        /// <remarks/>
        public int OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OrderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RequiredDate {
            get {
                return this.requiredDateField;
            }
            set {
                this.requiredDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ShippedDate {
            get {
                return this.shippedDateField;
            }
            set {
                this.shippedDateField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        public int CustomerNumber {
            get {
                return this.customerNumberField;
            }
            set {
                this.customerNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BuscarCustumersCompletedEventHandler(object sender, BuscarCustumersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarCustumersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarCustumersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Custumers Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Custumers)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BuscarOrdenCompletedEventHandler(object sender, BuscarOrdenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarOrdenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarOrdenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Ordes Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Ordes)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BuscarEmployeesCompletedEventHandler(object sender, BuscarEmployeesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarEmployeesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarEmployeesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Employees Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Employees)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BuscarProductoCompletedEventHandler(object sender, BuscarProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Products[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Products[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591